/**
 * @fileoverview gRPC-Web generated client stub for services.drawActivity.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: src/proto/v1/draw-activity/drawActivity.service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_v1_draw$activity_drawActivity_service_pb from '../../../../src/proto/v1/draw-activity/drawActivity.service_pb';


export class DrawActivityGrpcClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPreditRectangularCoordinate = new grpcWeb.MethodDescriptor(
    '/services.drawActivity.v1.DrawActivityGrpc/PreditRectangularCoordinate',
    grpcWeb.MethodType.UNARY,
    src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateRequest,
    src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateResponse,
    (request: src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateRequest) => {
      return request.serializeBinary();
    },
    src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateResponse.deserializeBinary
  );

  preditRectangularCoordinate(
    request: src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateRequest,
    metadata: grpcWeb.Metadata | null): Promise<src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateResponse>;

  preditRectangularCoordinate(
    request: src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateResponse) => void): grpcWeb.ClientReadableStream<src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateResponse>;

  preditRectangularCoordinate(
    request: src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_v1_draw$activity_drawActivity_service_pb.PreditRectangularCoordinateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/services.drawActivity.v1.DrawActivityGrpc/PreditRectangularCoordinate',
        request,
        metadata || {},
        this.methodDescriptorPreditRectangularCoordinate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/services.drawActivity.v1.DrawActivityGrpc/PreditRectangularCoordinate',
    request,
    metadata || {},
    this.methodDescriptorPreditRectangularCoordinate);
  }

}

