/**
 * @fileoverview gRPC-Web generated client stub for services.machineLearning.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: src/proto/v1/machine-learning/machineLearning.service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_v1_machine$learning_machineLearning_service_pb from '../../../../src/proto/v1/machine-learning/machineLearning.service_pb';


export class MachineLearningGrpcClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateMachineLearning = new grpcWeb.MethodDescriptor(
    '/services.machineLearning.v1.MachineLearningGrpc/CreateMachineLearning',
    grpcWeb.MethodType.UNARY,
    src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningRequest,
    src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse,
    (request: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningRequest) => {
      return request.serializeBinary();
    },
    src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse.deserializeBinary
  );

  createMachineLearning(
    request: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningRequest,
    metadata: grpcWeb.Metadata | null): Promise<src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse>;

  createMachineLearning(
    request: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse) => void): grpcWeb.ClientReadableStream<src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse>;

  createMachineLearning(
    request: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/services.machineLearning.v1.MachineLearningGrpc/CreateMachineLearning',
        request,
        metadata || {},
        this.methodDescriptorCreateMachineLearning,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/services.machineLearning.v1.MachineLearningGrpc/CreateMachineLearning',
    request,
    metadata || {},
    this.methodDescriptorCreateMachineLearning);
  }

  methodDescriptorUpdateMachineLearning = new grpcWeb.MethodDescriptor(
    '/services.machineLearning.v1.MachineLearningGrpc/UpdateMachineLearning',
    grpcWeb.MethodType.UNARY,
    src_proto_v1_machine$learning_machineLearning_service_pb.UpdateMachineLearningRequest,
    src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse,
    (request: src_proto_v1_machine$learning_machineLearning_service_pb.UpdateMachineLearningRequest) => {
      return request.serializeBinary();
    },
    src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse.deserializeBinary
  );

  updateMachineLearning(
    request: src_proto_v1_machine$learning_machineLearning_service_pb.UpdateMachineLearningRequest,
    metadata: grpcWeb.Metadata | null): Promise<src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse>;

  updateMachineLearning(
    request: src_proto_v1_machine$learning_machineLearning_service_pb.UpdateMachineLearningRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse) => void): grpcWeb.ClientReadableStream<src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse>;

  updateMachineLearning(
    request: src_proto_v1_machine$learning_machineLearning_service_pb.UpdateMachineLearningRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_v1_machine$learning_machineLearning_service_pb.CreateMachineLearningResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/services.machineLearning.v1.MachineLearningGrpc/UpdateMachineLearning',
        request,
        metadata || {},
        this.methodDescriptorUpdateMachineLearning,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/services.machineLearning.v1.MachineLearningGrpc/UpdateMachineLearning',
    request,
    metadata || {},
    this.methodDescriptorUpdateMachineLearning);
  }

}

