FROM    alpine:3.15.1 AS build

WORKDIR /app

RUN     apk add --no-cache protoc

COPY    ./src/proto/v1/ .

# build proto descriptor
RUN     protoc --include_imports --include_source_info \
    --descriptor_set_out=file.service.pb ./**/*.proto

FROM    envoyproxy/envoy:v1.22.0

COPY    --from=build /app/ /tmp/